name: release-beta
on:
  push:
    tags: ['*beta*']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          test -n "$NPM_TOKEN"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          bun install
          bun publish --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
