name: release
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'beta') }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          test -n "$NPM_TOKEN"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          bun install
          bun run build
          bun publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
