name: release-beta
on:
  push:
    tags: ['*beta*']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: |
          test -n "$NPM_TOKEN"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          yarn install
          npm publish --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
